name: Generate Daily Zmanim JSON for Loxone

on:
  schedule:
    - cron: '0 1 * * *' # Elke nacht om 01:00 UTC (03:00 Nederlandse zomertijd)
  workflow_dispatch: # Dit zorgt ervoor dat we dadelijk handmatig op een knop kunnen drukken om te testen

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Zmanim script
        env:
          TIMEZONE: "Europe/Amsterdam"
          LATITUDE: "52.3676"          # <-- VERVANG DIT DOOR JOUW LATITUDE (BREEDTEGRAAD)
          LONGITUDE: "4.9041"          # <-- VERVANG DIT DOOR JOUW LONGITUDE (LENGTEGRAAD)
          CITY: "MijnHuis"
        run: python main.py

      - name: Commit and Push JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add zmanim.json
          git commit -m "Update daily zmanim JSON" || exit 0
          git push
